---
title: "Welcome"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output: 
  html_document: rmdformats::readthedown
---

# About
This site was made by Randi Bolt, an undergrad mathematics and statistics student at Portland State University for Statistics - 451 : Applied Statistics for Engineers and Scientists during the Summer of 2021. Most of the definitions,  theorems, example problems and homework problems are from the book *Probability and Statistics for Engineering and the Sciences, Enhanced Edition, 9th ed.*, with some class examples and notes from Subhash Kochar. Other than that the rest of the site and work (both in homework and examples) is my own. 

Each chapter is shown in the nav. bar, along with with homework (HW) problems that cover the material in that chapter. 

Each chapter is divided into three sections : Definitions, Theorems, and Examples. 

For questions, comments, or curiosity check out the contact page for my email, and other projects I have worked on during my undergraduate degree. 

Enjoy :D

